Added New Options
TheDragonCode/migrate-db pull request #15
Opened 2022-02-06 11:45 UTC by Jagdish-J-P

- Added New options and interactive input options while migrating databases. 

- Added option to choose whether truncate table or append to existing tables from last migration in case if transfer is interrupted between migration on large database.

tables - This option will migrate only specified tables
exclude-tables - This option will exclude specified tables from migrations

2022-02-06 13:11 UTC, andrey-helldar requested changes
Enable EditorConfig support in your development environment and apply code auto-formatting.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        return explode(',', $this->validatedOption('exclude-tables'));
Move the separator to a property.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +            ['target', 'both', 'none'],
1. Move the question to a separate method.
2. Move options to a property.
3. Write the question in one line.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->tableNames =   $this->tableNames();
1. Extra space characters.
2. There is no alignment of values in the group.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->excludeTables =   $this->excludeTables();
1. Extra space characters.
2. There is no alignment of values in the group.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if ($this->tableNames[0] == '-' && $this->confirm('Get all table list from target connection(incase if source connection does not support it)?', false))
1. Use strict comparison - `===`.
2. Move the question to a separate method.
3. Missing a space character in the question.
4. The logical block is not wrapped in curly braces.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if ($this->confirm('Please choose option whether to truncate target table before transfer?', false))
1. Move the question to a separate method.
2. The logical block is not wrapped in curly braces.

2022-02-06 13:11 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if (($this->tableNames[0] == '-'
1. Use strict comparison - `===`.
2. Move the comparison to a separate method.
3. The logical block is not wrapped in curly braces.

2022-02-06 13:27 UTC, andrey-helldar requested changes

2022-02-06 13:27 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        return $this->tableNames[0] != '-'
By the way, why can the name of the first table be a minus sign?

By default, if the parameter is missing, `null` is returned.

2022-02-06 13:29 UTC, andrey-helldar commented
Also, you haven't covered the code with tests.

2022-02-06 14:09 UTC, Jagdish-J-P commented on src/Console/Migrate.php
> +    protected bool $getTablesFromTarget = false;
changed to retrive_tables_from_target.

2022-02-06 14:20 UTC, Jagdish-J-P commented on src/Console/Migrate.php
> +    protected array $tableNames;
Resolved

2022-02-06 14:20 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected bool $getTablesFromTarget = false;
The title is too long. This is PHP, not JS. You do not need to include the entire sentence in the variable name.

2022-02-06 16:12 UTC, Jagdish-J-P commented on src/Console/Migrate.php
> +        Log::info('Transferring data from:' . $table);
Removed information from console output as it was breaking progress bar.  This log is added to log which table is processed last if migration is interrupted in between for larger database.

2022-02-06 16:18 UTC, Jagdish-J-P commented on src/Console/Migrate.php
> +                    Log::info('last record:' . ($lastRecord = $this->builder($this->target(), $table)->max($column) ?? 0));
Removed Information from Console output as it was breaking progress bar. This added to log from which record data has started insertion.

2022-02-06 16:36 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        . ' {--get-all-tables-from-target=false : Get all tables from target connection if source connection do not support.}'
https://laravel.com/docs/8.x/artisan#options

2022-02-06 18:18 UTC, andrey-helldar requested changes

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +            $this->call('migrate', ['--database' => $this->source()]);
Since you are given the choice of running migrations, you need to get rid of code duplication.

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +            $this->call('migrate', ['--database' => $this->target()]);
Since you are given the choice of running migrations, you need to get rid of code duplication.

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function getMigrationOption()
Add method return typing: `: bool`

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function resolveTableListOption()
1. Add method return typing: `: bool`
2. The method for requesting information from the user cannot begin with the word "resolve". You need to use "get".

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function resolveTruncateTableOption()
1. Add method return typing: `: bool`
2. The method for requesting information from the user cannot begin with the word "resolve". You need to use "get".

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function resolveDropOption()
1. Add method return typing: `: bool`
2. The method for requesting information from the user cannot begin with the word "resolve". You need to use "get".

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->retrive_tables_from_target   = false;
The initial state of a parameter must be defined in the class, not in the called method.

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->truncate_tables              = false;
The initial state of a parameter must be defined in the class, not in the called method.

2022-02-06 18:18 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->drop_target_tables           = false;
The initial state of a parameter must be defined in the class, not in the called method.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            '--tables'      => implode(',', [$this->table_foo, $this->table_bar]),
```suggestion
            '--tables'      => [$this->table_foo, $this->table_bar],
```

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +
An unnecessary empty string.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +
An unnecessary empty string.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +            '--exclude-tables'      => implode(',', [$this->table_foo, $this->table_bar]),
```suggestion
            '--exclude-tables'      => [$this->table_foo, $this->table_bar],
```

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +        ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> +        ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            '--tables'      => implode(',', [$this->table_foo, $this->table_bar]),
```suggestion
            '--tables'      => [$this->table_foo, $this->table_bar],
```

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +
An unnecessary empty string.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +
An unnecessary empty string.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            '--exclude-tables'      => implode(',', [$this->table_foo, $this->table_bar]),
```suggestion
            '--exclude-tables'      => [$this->table_foo, $this->table_bar],
```

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/MysqlToPostgresTest.php
> +        ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            '--tables'      => implode(',', [$this->table_foo, $this->table_bar]),
```suggestion
            '--tables'      => [$this->table_foo, $this->table_bar],
```

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +
An unnecessary empty string.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
The `run` method needs to be moved to a new line.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +
An unnecessary empty string.

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            '--exclude-tables'      => implode(',', [$this->table_foo, $this->table_bar]),
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +        ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +        ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            '--tables'      => implode(',', [$this->table_foo, $this->table_bar]),
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            '--exclude-tables'      => implode(',', [$this->table_foo, $this->table_bar]),
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +            ->assertExitCode(0)->run();
Here

2022-02-06 18:18 UTC, andrey-helldar commented on tests/Unit/PostgresToPostgresTest.php
> +        ->assertExitCode(0)->run();
Here

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 09:01 UTC, andrey-helldar commented on tests/Unit/PostgresToMysqlTest.php
> +			->run();
1. We do not use tab indentation.
2. Too much indentation.

2022-02-07 11:29 UTC, andrey-helldar requested changes

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +            if ($this->hasTable($this->source(), $table) === false) {
```php
protected function runTransfer(): void
{
    // ...
    if ($this->doesntTable($this->source(), $table)) {
        // ...
    }
    // ...
}

protected function doesntTable(string $connection, string $table): bool
{
    return ! $this->hasTable($connection, $table);
}
```

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +                    return $query->where($column, '>', $lastRecord);
An empty line indent is missing.

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        return $this->truncate === false && $this->isNumericColumn($table, $column);
```php
return ! $this->truncate && $this->isNumericColumn($table, $column);
```

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if (empty($this->tables) === false) {
```php
if (! empty($this->tables)) {
```

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if ($this->drop_target === false) {
```php
if (! $this->drop_target) {
```

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if ($this->isMigrationRequired($run_migration_on) === false) {
```php
if (! $this->isMigrationRequired($run_migration_on)) {
```

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        return $this->drop_target === true || in_array($run_migration_on, [$this->target_connection, $this->both_connection]);
```php
return $this->drop_target || $this->shouldRunOnSource($connection) || $this->shouldRunOnTarget($connection);

// add a new method
protected function shouldRunOnTarget(string $connection): bool
{
    return $connection === $this->target_connection;
}
```

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function isNumericColumn($table, $column): bool
`string $table, string $column`

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    /**  if primary key is not string then skipping existing records */
Methods need to have a full docking block, not an inline one.

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function isMigrationRequired($run_migration_on): bool
`string $connection`

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function shouldRunOnTarget($run_migration_on): bool
Rename method and add variable typing: `shouldRun(string $connection)`

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function shouldRunOnSource($run_migration_on): bool
`string $run_migration_on`

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function migrate($connection): void
`string $connection`

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->tables                       = $this->getTablesOption();
Remove unnecessary spaces

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->excludes                     = $this->getExcludeOption();
Remove unnecessary spaces

2022-02-07 11:29 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        if ((empty($this->tables) && empty($this->excludes) && $this->truncate && $this->confirmDropOption())) {
```suggestion
        if (empty($this->tables) && empty($this->excludes) && $this->truncate && $this->confirmDropOption()) {
```

2022-02-07 12:05 UTC, Jagdish-J-P commented on src/Console/Migrate.php
> +        $this->displayMessage(PHP_EOL);
Could not get your point

2022-02-08 08:24 UTC, andrey-helldar requested changes
Apply code auto-formatting.

2022-02-08 08:24 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected $retrive_tables_from_target = false;
```suggestion
    protected $retrieve_tables_from_target = false;
```

2022-02-08 08:24 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function displayMessage(string $message, array $context = []): void
There is no indent from the previous method. Use code auto-formatting.

2022-02-08 08:24 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        $this->displayMessage(PHP_EOL);
The message was to another line. GitHub moved it for some reason.

2022-02-08 08:24 UTC, andrey-helldar commented on src/Console/Migrate.php
> +     * */
1. The method is self-documenting;
2. There is no need for this dock block.

Besides:
1. The sentence starts with a small letter;
2. There is no full stop at the end of the sentence;
3. Before listing variables there is no indent in the form of an empty line;
4. The dock block ends incorrectly - `*/` must be specified on a new line along with other asterisks.

2022-02-08 08:26 UTC, andrey-helldar requested changes

2022-02-08 08:26 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function isMigrationNotRequired(string $run_migration_on): bool
You can shorten the variable name to `$on`.

2022-02-08 08:26 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function shouldRunOnTarget(string $run_migration_on): bool
You can shorten the variable name to `$on`.

2022-02-08 08:26 UTC, andrey-helldar commented on src/Console/Migrate.php
> +    protected function shouldRunOnSource(string $run_migration_on): bool
You can shorten the variable name to `$on`.

2022-02-08 12:30 UTC, andrey-helldar requested changes

2022-02-08 12:30 UTC, andrey-helldar commented on src/Console/Migrate.php
> +        return  $this->retrive_tables_from_target
```suggestion
        return  $this->retrieve_tables_from_target
```

Old name.

2022-02-08 12:30 UTC, andrey-helldar commented on src/Console/Migrate.php
> +            $this->retrive_tables_from_target = true;
```suggestion
            $this->retrieve_tables_from_target = true;
```

Old name.

2022-02-08 12:31 UTC, andrey-helldar requested changes

2022-02-08 12:31 UTC, andrey-helldar commented on tests/Concerns/Database.php
> +    protected $choice_none = 'none';
![image](https://user-images.githubusercontent.com/10347617/152987565-c59f591d-2544-47b4-b60b-d6992af6859f.png)

2022-02-09 11:07 UTC, andrey-helldar commented
Tests doesn't work too.

For example:

![image](https://user-images.githubusercontent.com/10347617/153186289-0d7a8675-6f9e-4af8-9ed0-f70fadd9a018.png)

https://github.com/TheDragonCode/migrate-db/runs/5124067520?check_suite_focus=true

2022-02-12 09:48 UTC, andrey-helldar requested changes
It remains to fix the tests.

2022-02-12 11:26 UTC, andrey-helldar commented
Can you add `doctrine/dbal` dependency?

2022-02-12 13:39 UTC, andrey-helldar requested changes

2022-02-12 13:39 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> -            ->expectsConfirmation('Please confirm table list should be retrieved from target connection? (incase if source connection does not support it)', 'no')
Why are you deleting this question?

In code, if tables is not empty, it must be set: https://github.com/Jagdish-J-P/migrate-db/blob/main/src/Console/Migrate.php#L307

2022-02-12 13:43 UTC, andrey-helldar commented on tests/Unit/MysqlToMysqlTest.php
> -            ->expectsConfirmation('Please confirm table list should be retrieved from target connection? (incase if source connection does not support it)', 'no')
Ah, ok.

2022-02-12 13:54 UTC, andrey-helldar commented
Congratulations. All tests passed.

Now I have to make sure the data transfer is correct.

2022-02-12 13:54 UTC, Jagdish-J-P commented
> ![image](https://user-images.githubusercontent.com/10347617/153713972-e940ac68-6219-468f-98ae-ab90b75f322b.png)
> 
> For example, in one of the tests, the table is expected to have 6 rows, but only 3 are found.
> 
> Why is this happening? Is the test written incorrectly or is the data not fully transferred?

That test will fail if table has primary key with bin integer or integer type. because code is written to skip existing records which can be checked if type is integer.

This test will pass if primary key type is text or string like uuid field.

2022-02-12 14:05 UTC, andrey-helldar commented
### Source

![image](https://user-images.githubusercontent.com/10347617/153714439-6b942618-ee0a-48d1-a2cc-f16f05c7b34d.png)

### Target

![image](https://user-images.githubusercontent.com/10347617/153714451-c9bb8120-bc01-4dfe-b7b9-e06b817fa5e9.png)

### Console

![image](https://user-images.githubusercontent.com/10347617/153714500-751e3904-448a-46ca-a120-edb80da6f176.png)

### Database

![image](https://user-images.githubusercontent.com/10347617/153714509-be9322f3-f4ac-4574-a426-768b20baf329.png)

2022-02-12 14:07 UTC, Jagdish-J-P commented
> ### Source
> ![image](https://user-images.githubusercontent.com/10347617/153714439-6b942618-ee0a-48d1-a2cc-f16f05c7b34d.png)
> 
> ### Target
> ![image](https://user-images.githubusercontent.com/10347617/153714451-c9bb8120-bc01-4dfe-b7b9-e06b817fa5e9.png)
> 
> ### Console
> ![image](https://user-images.githubusercontent.com/10347617/153714500-751e3904-448a-46ca-a120-edb80da6f176.png)
> 
> ### Database
> ![image](https://user-images.githubusercontent.com/10347617/153714509-be9322f3-f4ac-4574-a426-768b20baf329.png)

Both Are MySQL database?

2022-02-12 14:11 UTC, andrey-helldar commented
Yep, MySQL 8.0.28

![image](https://user-images.githubusercontent.com/10347617/153714635-4db7db74-909e-408c-9dea-cb38caab2d50.png)

## Info

If I migrate to a database that already has data, then everything is fine:

![image](https://user-images.githubusercontent.com/10347617/153714685-d8b29239-6086-4a09-9373-28c84df21c61.png)

### BUT

If I execute on a completely clean base, I get an error:

![image](https://user-images.githubusercontent.com/10347617/153714709-471c1834-00d4-4460-a03a-03efebb51a42.png)

![image](https://user-images.githubusercontent.com/10347617/153714726-ba741c29-4f58-4ca5-bf73-a969e949bb5a.png)

2022-02-12 14:13 UTC, andrey-helldar commented
![image](https://user-images.githubusercontent.com/10347617/153714763-98619701-2e43-4cbe-8e18-06fd1dc845a9.png)

![image](https://user-images.githubusercontent.com/10347617/153714765-ece21d59-306e-422c-9ca9-60683978b072.png)

By the way, I solved this problem.

I had `laravel/telescope` enabled the first time I ran it, and I disabled it before migrating. Therefore, the migration file was not deployed.

2022-02-12 14:14 UTC, andrey-helldar commented
You can also try in your environment.

Make the following changes to the `composer.json` file:

```json
{
    "require-dev": {
        "dragon-code/migrate-db": "dev-main",
    },
    "repositories": [
        {
            "type": "github",
            "url": "git@github.com:Jagdish-J-P/migrate-db.git"
        }
    ]
}
```

And run the `composer update` command.

2022-02-12 14:17 UTC, andrey-helldar commented
```
[2022-02-12 14:17:46] local.INFO: Transferring data from: failed_jobs  
[2022-02-12 14:17:46] local.ERROR: Class "Doctrine\DBAL\Driver\AbstractMySQLDriver" not found {"exception":"[object] (Error(code: 0): Class \"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver\" not found at D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\PDO\\MySqlDriver.php:8)
[stacktrace]
#0 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\composer\\ClassLoader.php(571): include()
#1 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\composer\\ClassLoader.php(428): Composer\\Autoload\\includeFile('D:\\\\domains\\\\drag...')
#2 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\MySqlConnection.php(89): Composer\\Autoload\\ClassLoader->loadClass('Illuminate\\\\Data...')
#3 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(1007): Illuminate\\Database\\MySqlConnection->getDoctrineDriver()
#4 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(990): Illuminate\\Database\\Connection->getDoctrineConnection()
#5 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(978): Illuminate\\Database\\Connection->getDoctrineSchemaManager()
#6 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(332): Illuminate\\Database\\Connection->getDoctrineColumn('failed_jobs', 'id')
#7 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(162): DragonCode\\MigrateDB\\Console\\Migrate->getPrimaryKeyType('mysql', 'failed_jobs', 'id')
#8 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(157): DragonCode\\MigrateDB\\Console\\Migrate->isNumericColumn('failed_jobs', 'id')
#9 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(136): DragonCode\\MigrateDB\\Console\\Migrate->isSkippable('failed_jobs', 'id')
#10 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(117): DragonCode\\MigrateDB\\Console\\Migrate->migrateTable('failed_jobs', 'id')
#11 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php(258): DragonCode\\MigrateDB\\Console\\Migrate->DragonCode\\MigrateDB\\Console\\{closure}('failed_jobs', Object(Symfony\\Component\\Console\\Helper\\ProgressBar))
#12 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(118): Illuminate\\Console\\Command->withProgressBar(Array, Object(Closure))
#13 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(77): DragonCode\\MigrateDB\\Console\\Migrate->runTransfer()
#14 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): DragonCode\\MigrateDB\\Console\\Migrate->handle()
#15 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#20 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Command\\Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Application.php(989): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(DragonCode\\MigrateDB\\Console\\Migrate), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 D:\\domains\\dragon-code\\apps\\webhooks\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"} 
```

2022-02-12 14:20 UTC, Jagdish-J-P commented
How did you install new changes of this pull request to your local project?

2022-02-12 14:22 UTC, andrey-helldar commented
Hm... 

![image](https://user-images.githubusercontent.com/10347617/153715019-a4f1deef-dacf-4a15-9f41-e09113b3784e.png)

My bad. Moved `doctrine/dbal` to `require-dev` 😅

2022-02-12 14:23 UTC, andrey-helldar commented
> How did you install new changes of this pull request to your local project?

That: https://github.com/TheDragonCode/migrate-db/pull/15#issuecomment-1037237308

2022-02-12 14:24 UTC, andrey-helldar commented
New error)

![image](https://user-images.githubusercontent.com/10347617/153715142-6be19ba5-0607-4a0a-a3a9-477306033ffd.png)

```
[2022-02-12 14:25:19] local.INFO: Transferring data from: failed_jobs  
[2022-02-12 14:25:19] local.INFO: last record:   
[2022-02-12 14:25:19] local.ERROR: Illegal operator and value combination. {"exception":"[object] (InvalidArgumentException(code: 0): Illegal operator and value combination. at D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php:811)
[stacktrace]
#0 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(707): Illuminate\\Database\\Query\\Builder->prepareValueAndOperator(NULL, '>', false)
#1 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(142): Illuminate\\Database\\Query\\Builder->where('id', '>', NULL)
#2 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Conditionable\\Traits\\Conditionable.php(29): DragonCode\\MigrateDB\\Console\\Migrate->DragonCode\\MigrateDB\\Console\\{closure}(Object(Illuminate\\Database\\Query\\Builder), true)
#3 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(143): Illuminate\\Database\\Query\\Builder->when(true, Object(Closure))
#4 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(117): DragonCode\\MigrateDB\\Console\\Migrate->migrateTable('failed_jobs', 'id')
#5 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php(258): DragonCode\\MigrateDB\\Console\\Migrate->DragonCode\\MigrateDB\\Console\\{closure}('failed_jobs', Object(Symfony\\Component\\Console\\Helper\\ProgressBar))
#6 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(118): Illuminate\\Console\\Command->withProgressBar(Array, Object(Closure))
#7 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\dragon-code\\migrate-db\\src\\Console\\Migrate.php(77): DragonCode\\MigrateDB\\Console\\Migrate->runTransfer()
#8 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): DragonCode\\MigrateDB\\Console\\Migrate->handle()
#9 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#14 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Command\\Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Application.php(989): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(DragonCode\\MigrateDB\\Console\\Migrate), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 D:\\domains\\dragon-code\\apps\\webhooks\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 D:\\domains\\dragon-code\\apps\\webhooks\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
```

2022-02-12 14:26 UTC, andrey-helldar commented
![image](https://user-images.githubusercontent.com/10347617/153715193-0a1518a6-411a-4205-9f7e-e45548b1c030.png)

2022-02-12 14:26 UTC, andrey-helldar commented
Very nice!

Thanks for the hard job! 💪

![image](https://user-images.githubusercontent.com/10347617/153715208-baa2a974-1083-4f76-b48b-dad5717dcceb.png)

2022-02-12 14:33 UTC, andrey-helldar approved these changes

2022-02-12 14:34 UTC, merged

2022-02-12 14:34 UTC, Jagdish-J-P commented
Thank You. This was my first pull request in public repository. Learnt a lot. I have recently started in Laravel. I have used this package to transfer 2 million records from SQL Server to MySQL. While transferring I faced some issues. So I had modified your package as per my requirement and made changes according to in this pull request.

2022-02-12 14:35 UTC, andrey-helldar commented
You have added a very cool feature. I originally wrote a package for my work to migrate data from Postgres to MySQL :)

2022-02-12 14:36 UTC, andrey-helldar commented
And thanks to you, I was finally able to write a [`linter`](https://github.com/TheDragonCode/php-codestyler) 😁

2022-02-12 14:37 UTC, andrey-helldar commented
Released: [`v2.2.0`](https://github.com/TheDragonCode/migrate-db/releases/tag/v2.2.0)